function survey = compute_nadir_pointing_aero_survey(altitude_km, varargin)
    parser = inputParser();
    parser.addRequired('altitude_km', @(x) isscalar(x) && isfinite(x) && x > 0);
    parser.addParameter('nOrbits', 3, @(x) isscalar(x) && isfinite(x) && x >= 1);
    parser.addParameter('samplesPerOrbit', 120, @(x) isscalar(x) && isfinite(x) && x >= 10);
    parser.addParameter('gsi_model', 'cook', @(x) ischar(x) || isstring(x));
    parser.addParameter('thrusterLayoutMode', 'standard', @(x) islogical(x) || ischar(x) || isstring(x));
    parser.addParameter('Isp_s', 760, @(x) isscalar(x) && isfinite(x) && x > 0);
    parser.addParameter('usableFuelMass_kg', 1.5, @(x) isscalar(x) && isfinite(x) && x > 0);
    parser.addParameter('showProgress', false, @(x) islogical(x) && isscalar(x));
    parser.parse(altitude_km, varargin{:});

    opts = parser.Results;
    gsiModel = char(opts.gsi_model);

    c = vleo.util.constants();

    altitude_m = opts.altitude_km * 1e3;
    orbitRadius_m = c.R_earth + altitude_m;
    meanMotion = sqrt(c.mu_earth / orbitRadius_m^3);
    orbitalPeriod_s = 2 * pi / meanMotion;
    totalTime_s = opts.nOrbits * orbitalPeriod_s;

    nSamples = opts.nOrbits * opts.samplesPerOrbit + 1;
    tSec = linspace(0, totalTime_s, nSamples).';

    time0 = struct('year', 2002, 'dayOfYear', 106, 'UTseconds', 43200);
    objFile = vleo.util.geometry_asset_path('6U CubeSat.obj');
    aeroOpts = struct( ...
        'f107Average', 150, ...
        'f107Daily', 150, ...
        'magneticIndex', ones(1, 7) * 3, ...
        'anomalousOxygen', 0, ...
        'gsi_model', gsiModel, ...
        'alpha', 1, ...
        'Tw', 300, ...
        'enableShadow', 0, ...
        'enableSolar', 0 ...
    );

    attitude = struct('aoa', 180, 'aos', 0);

    forceBody_N = zeros(nSamples, 3);
    torqueBody_Nm = zeros(nSamples, 3);
    density_kg_m3 = zeros(nSamples, 1);

    for idx = 1:nSamples
        theta = meanMotion * tSec(idx);
        posEci = orbitRadius_m * [cos(theta); sin(theta); 0];

        timeNow = time0;
        timeNow.UTseconds = time0.UTseconds + tSec(idx);

        aeroResult = vleo.aero.compute_aero_forces(objFile, ...
            struct('positionECI', posEci), attitude, timeNow, aeroOpts);

        dynamicPressure = 0.5 * aeroResult.rho * aeroResult.vinf^2;
        forceBody_N(idx, :) = (dynamicPressure * aeroResult.AreaRef * aeroResult.Cf_b).';
        torqueBody_Nm(idx, :) = aeroResult.M_aero.';
        density_kg_m3(idx) = aeroResult.rho;

        if opts.showProgress && mod(idx, 60) == 0
            fprintf('  %d / %d  (%.0f%%)\n', idx, nSamples, 100 * idx / nSamples);
        end
    end

    params = vleo.dynamics.default_control_test_params(true);
    layout = vleo.control.corner_thruster_layout(params, opts.thrusterLayoutMode);
    requiredWrenchHistory = -[forceBody_N, torqueBody_Nm];
    thrusterForces_N = vleo.control.allocate_thruster_forces(requiredWrenchHistory, params, layout);
    totalThrusterForce_N = sum(thrusterForces_N, 2);
    averageTotalThrusterForce_N = mean(totalThrusterForce_N);

    g0 = 9.80665;
    massFlowRate_kg_s = averageTotalThrusterForce_N / (opts.Isp_s * g0);
    if averageTotalThrusterForce_N > 0
        missionLife_s = opts.usableFuelMass_kg / massFlowRate_kg_s;
    else
        missionLife_s = inf;
    end

    survey = struct( ...
        'altitude_km', opts.altitude_km, ...
        'nOrbits', opts.nOrbits, ...
        'samplesPerOrbit', opts.samplesPerOrbit, ...
        'gsi_model', gsiModel, ...
        'thruster_layout_mode', layout.mode, ...
        'time0', time0, ...
        'tSec', tSec, ...
        'timeMin', tSec / 60, ...
        'orbitalPeriod_s', orbitalPeriod_s, ...
        'totalTime_s', totalTime_s, ...
        'forceBody_N', forceBody_N, ...
        'torqueBody_Nm', torqueBody_Nm, ...
        'density_kg_m3', density_kg_m3, ...
        'requiredWrenchHistory', requiredWrenchHistory, ...
        'thrusterForces_N', thrusterForces_N, ...
        'totalThrusterForce_N', totalThrusterForce_N, ...
        'averageTotalThrusterForce_N', averageTotalThrusterForce_N, ...
        'Isp_s', opts.Isp_s, ...
        'usableFuelMass_kg', opts.usableFuelMass_kg, ...
        'massFlowRate_kg_s', massFlowRate_kg_s, ...
        'massFlowRate_g_day', massFlowRate_kg_s * 86400 * 1e3, ...
        'missionLife_s', missionLife_s, ...
        'missionLife_days', missionLife_s / 86400, ...
        'missionLife_years', missionLife_s / (86400 * 365.25), ...
        'layout', layout);
end
