function aliases = controller_name_aliases()
    aliases = containers.Map( ...
        {'control_torques', 'control_torques.m', 'myController', 'myController.m'}, ...
        {'vleo.control.attitude_pd_controller', 'vleo.control.attitude_pd_controller', ...
         'vleo.control.zero_torque_controller', 'vleo.control.zero_torque_controller'});
end
