function result = solve_minimax_attitude_slew_fast_legacy(qInitial, omegaInitialBody, qTarget, ...
        omegaTargetBody, inertiaBody, maneuverDuration, nIntervals, varargin)
    result = vleo.control.solve_minimax_attitude_slew_fast(qInitial, omegaInitialBody, qTarget, ...
        omegaTargetBody, inertiaBody, maneuverDuration, nIntervals, ...
        'objectiveMode', 'torque', varargin{:});
end
