function csvPath = save_torque_history_csv(filePrefix, tspan, visibilityHistory, ...
        tauTotalHistory, tauControlHistory, tauAeroHistory, includeAerodynamics, scenarioSeedText)
    simulationsDir = vleo.util.simulations_dir();
    timestamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
    csvName = sprintf('%s_torque_history_aero_%s_seed_%s_%s.csv', ...
        filePrefix, vleo.util.on_off_text(includeAerodynamics), scenarioSeedText, timestamp);
    csvPath = fullfile(simulationsDir, csvName);

    torqueTable = table(tspan(:), tspan(:) / 60, logical(visibilityHistory(:)), ...
        tauTotalHistory(:, 1), tauTotalHistory(:, 2), tauTotalHistory(:, 3), ...
        tauControlHistory(:, 1), tauControlHistory(:, 2), tauControlHistory(:, 3), ...
        tauAeroHistory(:, 1), tauAeroHistory(:, 2), tauAeroHistory(:, 3), ...
        'VariableNames', {'time_s', 'time_min', 'visible', ...
        'tau_total_x', 'tau_total_y', 'tau_total_z', ...
        'tau_actuator_x', 'tau_actuator_y', 'tau_actuator_z', ...
        'tau_aero_x', 'tau_aero_y', 'tau_aero_z'});

    writetable(torqueTable, csvPath);
end
