function csvPath = save_euler_history_csv(filePrefix, plotTime, desiredEulerDeg, actualEulerDeg, ...
        includeAerodynamics, scenarioSeedText)
    simulationsDir = vleo.util.simulations_dir();
    timestamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
    csvName = sprintf('%s_euler_history_aero_%s_seed_%s_%s.csv', ...
        filePrefix, vleo.util.on_off_text(includeAerodynamics), scenarioSeedText, timestamp);
    csvPath = fullfile(simulationsDir, csvName);

    eulerTable = table(plotTime(:), plotTime(:) / 60, ...
        desiredEulerDeg(:, 1), desiredEulerDeg(:, 2), desiredEulerDeg(:, 3), ...
        actualEulerDeg(:, 1), actualEulerDeg(:, 2), actualEulerDeg(:, 3), ...
        'VariableNames', {'time_s', 'time_min', ...
        'roll_desired_deg', 'pitch_desired_deg', 'yaw_desired_deg', ...
        'roll_actual_deg', 'pitch_actual_deg', 'yaw_actual_deg'});

    writetable(eulerTable, csvPath);
end
