function csvPath = save_attitude_history_csv(filePrefix, plotTime, desiredEulerDeg, actualEulerDeg, ...
        omegaBodyDesiredHistory, omegaBodyActualHistory, includeAerodynamics, scenarioSeedText)
    simulationsDir = vleo.util.simulations_dir();
    timestamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
    csvName = sprintf('%s_attitude_history_aero_%s_seed_%s_%s.csv', ...
        filePrefix, vleo.util.on_off_text(includeAerodynamics), scenarioSeedText, timestamp);
    csvPath = fullfile(simulationsDir, csvName);

    attitudeTable = table(plotTime(:), plotTime(:) / 60, ...
        desiredEulerDeg(:, 1), desiredEulerDeg(:, 2), desiredEulerDeg(:, 3), ...
        actualEulerDeg(:, 1), actualEulerDeg(:, 2), actualEulerDeg(:, 3), ...
        rad2deg(omegaBodyDesiredHistory(:, 1)), rad2deg(omegaBodyDesiredHistory(:, 2)), rad2deg(omegaBodyDesiredHistory(:, 3)), ...
        rad2deg(omegaBodyActualHistory(:, 1)), rad2deg(omegaBodyActualHistory(:, 2)), rad2deg(omegaBodyActualHistory(:, 3)), ...
        'VariableNames', {'time_s', 'time_min', ...
        'roll_desired_deg', 'pitch_desired_deg', 'yaw_desired_deg', ...
        'roll_actual_deg', 'pitch_actual_deg', 'yaw_actual_deg', ...
        'wx_desired_deg_s', 'wy_desired_deg_s', 'wz_desired_deg_s', ...
        'wx_actual_deg_s', 'wy_actual_deg_s', 'wz_actual_deg_s'});

    writetable(attitudeTable, csvPath);
end
