function simParams = default_simulation_params()
    c = vleo.util.constants();
    earthRadius = c.R_earth;
    simParams = struct();
    simParams.saved = false;
    simParams.named = false;
    simParams.fileName = 'My Simulation.mat';
    simParams.filePath = './simulations/My Simulation.mat';
    simParams.initParams = struct();
    simParams.initParams.Simulation = struct( ...
        'name', 'My Simulation', ...
        'type', 'Nonlinear', ...
        'initialTime', 0, ...
        'finalTime', 1000, ...
        'timeStep', 1, ...
        'relTol', 1e-6, ...
        'absTol', 1e-9);
    simParams.initParams.Orbit = struct( ...
        'altitude', 400e3, ...
        'semiMajorAxis', earthRadius + 400e3, ...
        'eccentricity', 0, ...
        'inclination', 0, ...
        'argPeriapse', 0, ...
        'RAAN', 0, ...
        'trueAnomaly', 0);
    simParams.initParams.Attitude = struct( ...
        'roll', 0, ...
        'pitch', 0, ...
        'yaw', 0, ...
        'rollRate', 0, ...
        'pitchRate', 0, ...
        'yawRate', 0, ...
        'Quaternion', [1, 0, 0, 0]);
    simParams.initParams.Environment = struct( ...
        'year', 2002, ...
        'secondsOfDay', 0, ...
        'dayOfYear', 1, ...
        'F107Average', 65, ...
        'F107Daily', 65, ...
        'magneticIndices', [3, 3, 3, 3, 3, 3, 3], ...
        'gasSurfaceInteractionModel', 'cook', ...
        'accommodationCoefficient', 1, ...
        'wallTemperature', 300, ...
        'specularReflectivity', 0.15, ...
        'diffuseReflectivity', 0.25, ...
        'enableAnomalousOxygen', false, ...
        'enableShadowAnalysis', true, ...
        'enableSolarRadiationPressure', true, ...
        'mu', c.mu_earth);
    simParams.initParams.Controller = struct( ...
        'functionName', 'vleo.control.attitude_pd_controller', ...
        'functionFile', 'vleo.control.attitude_pd_controller', ...
        'Func', @vleo.control.attitude_pd_controller);
    simParams.initParams.Modes = struct( ...
        'enableAero', true, ...
        'enableControl', true);
end
