function aeroConfig = build_aero_config_from_sim_params(simParams)
    vehicle = vleo.dynamics.default_vehicle_config();
    aeroConfig = struct();
    aeroConfig.objFilePath = vehicle.objFilePath;
    aeroConfig.mass = vehicle.mass;
    aeroConfig.year = vleo.util.get_env_value(simParams, 'year', 2002);
    aeroConfig.dayOfYear = vleo.util.get_env_value(simParams, 'dayOfYear', 1);
    aeroConfig.secondsOfDay = vleo.util.get_env_value(simParams, 'secondsOfDay', 0);
    aeroConfig.options = struct( ...
        'f107Average', vleo.util.get_env_value(simParams, 'F107Average', 150), ...
        'f107Daily', vleo.util.get_env_value(simParams, 'F107Daily', 150), ...
        'magneticIndex', vleo.util.get_env_value(simParams, 'magneticIndices', ones(1, 7) * 3), ...
        'anomalousOxygen', vleo.util.get_env_value(simParams, 'enableAnomalousOxygen', false), ...
        'gsi_model', vleo.util.normalize_gsi_model(vleo.util.get_env_value(simParams, 'gasSurfaceInteractionModel', 'cook')), ...
        'alpha', vleo.util.get_env_value(simParams, 'accommodationCoefficient', 1), ...
        'Tw', vleo.util.get_env_value(simParams, 'wallTemperature', 300), ...
        'enableShadow', vleo.util.get_env_value(simParams, 'enableShadowAnalysis', true), ...
        'enableSolar', vleo.util.get_env_value(simParams, 'enableSolarRadiationPressure', true), ...
        'sol_cR', vleo.util.get_env_value(simParams, 'specularReflectivity', 0.15), ...
        'sol_cD', vleo.util.get_env_value(simParams, 'diffuseReflectivity', 0.25));
end
