function inertiaBody = cuboid_inertia_matrix(mass, bodyDims)
    inertiaBody = (mass / 12) * diag([ ...
        bodyDims(2)^2 + bodyDims(3)^2, ...
        bodyDims(1)^2 + bodyDims(3)^2, ...
        bodyDims(1)^2 + bodyDims(2)^2]);
end
