function Xd = sat_dynamics_nonlinear(t, X)
    c = vleo.util.constants();
    tauControl = vleo.control.attitude_pd_controller(t, X);
    Xd = vleo.dynamics.sat_dynamics_base(t, X, c.mu_earth, default_aero_config(), tauControl);
end

function aeroConfig = default_aero_config()
    vehicle = vleo.dynamics.default_vehicle_config();
    aeroConfig = struct();
    aeroConfig.objFilePath = vehicle.objFilePath;
    aeroConfig.mass = vehicle.mass;
    aeroConfig.year = 2002;
    aeroConfig.dayOfYear = 106;
    aeroConfig.secondsOfDay = 0;
    aeroConfig.options = default_aero_options();
end

function options = default_aero_options()
    options = struct( ...
        'f107Average', 150, ...
        'f107Daily', 150, ...
        'magneticIndex', ones(1, 7) * 3, ...
        'anomalousOxygen', 0, ...
        'gsi_model', 'cook', ...
        'alpha', 1, ...
        'Tw', 300, ...
        'enableShadow', 1, ...
        'enableSolar', 1, ...
        'sol_cR', 0.15, ...
        'sol_cD', 0.25);
end
